{{- if eq "gitops-demo-stage" .Release.Namespace }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quinoa-wind-turbine
  namespace: gitops-demo-stage
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    developer-user-password: AgAyz3DSo8tVoM6ihX2Pn9AYbkrPTmKgzCRabVFnTzi6l5NQQqALj7IXHYs/Z1CtwGmQ4Hbl2COlbvnURD4zFB6EIYyfQ4xgYCeHG4VkN/CIzDQxM243NRnVi3NVYSnalcAE+P8KXoSXC7FnbwLYnHjP3Sf41NmTiHGxqwGWDrx2i7nCqWp2CE9Qmj6sc5pfwrISyzPTDMjpH4P+K/Bt1212VKC/pzrI1JnZwfpiC6qP7PbyHpXFLifl8iBmIjn8MyZq9l/C4zQhzTqr9PpgTED5wEJz5rTkrcw4w4zz4lkR7H20eeVlW7mi5N/du94X+qI+OtvHB8xaCZgV5/m2a29S9VbtI+CUXnpZ/00PJVpUpzri5JbP5ZcdowNp6ZV5lyFQ26J7y1F0St+VEZop1M72ES0HWKopHVt42KKaSly+RAM/wY650EUqO20nH5vH9ZeO848xL8blv19tNA1Gf/TbB+we/wkwPGYy28xba+sXGfOy/hsjoJFC/vSiq2jntAe9k0B+XonaEIqijttG3ghxOegq6Jzj7EheMwZJ9iu+HXcPa0XYVdyCehF76rVH6PBFcHt6MMHFDhLZ3XeGzN0LnsGCB1i1HDb0JB4jywObIR3azTPyEe7t1sJEgRQ8UuJvpCsAQMi0jL1pQfrfHUfwknCxsoPw86B/uoJgy6ctkLuaQdWR5Yx1NJnLn5oa3sVyYJ4H/GMbPw==
    plain-text-password-enabled: AgBzHAxYrkq2f78/erKlOAX1LKm/5th981gVH1sDE2JdznTNL/otWUyPBPrpLL1pYhQHgyP2hLOhW1VCejeA4dhdbK+g0gPnRtoar7xqXfPYasDNU1RKSHCIWB+zzpethcUnigP/fDvawbzyJTYvjsz04gq6t9PH9OKbXEPRQ53jPTYa1ngW1L1lNsLjWrspfvNOkJ+eYY3HQv7M+x0qsXSIydJgTVRv1HQfXL0VfkacTkqGzOuj3oLbOrGWmh4mq/2cjZ5VQOPyMA5lh8sai6j4O4mlQL79flI3vjamxmNjcFvYfqI2aMGaHfOH0H/Gvy7rmQQVdseqHyYnq5P10+gAIWUAXcLlgiCUs0ASgRCruKdpS584XDZBrZkFdyQ4eIs9pBj13V4eaViTxueZSyw7TIPB+PETkQWTuoQsj95HLO1P6oxMluT6Z3l/fk0cLhUDoTaBLi5WXQjhKDiC8Bo71APUD9YJEBz4/k74Ji0UVP70iC21NO40pMxi5RzZUm/qgc/m7z5CTT249E3A6RMD1a7jXii7qzjIiKDsZRnOH8jxEQXqU6WpKr/hO3oTDjfEJVUc+5jGXD4JVZ+jv8Y1b1xGj74fX3Bh38bTqdHbOY2ENc17FJvwgMGRHoIPMonYTd80nqFDL4uWHoiNiqnfntMGKD3ZizctrBPtl7PgHLB0I9lQ4wSCxGjbkmoFXBG6m+tk
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quinoa-wind-turbine
        app.kubernetes.io/component: quinoa-wind-turbine
        app.kubernetes.io/instance: quinoa-wind-turbine
        app.kubernetes.io/name: quinoa-wind-turbine
        app.kubernetes.io/part-of: wind-turbine
        app.openshift.io/runtime: quarkus
      name: quinoa-wind-turbine
      namespace: gitops-demo-stage
    type: Opaque
{{- end }}