{{- if eq "gitops-demo-prod" .Release.Namespace }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quinoa-wind-turbine
  namespace: gitops-demo-prod
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    developer-user-password: AgBA0whh3lAc55aGC32Gr6KqSWjSNKYbzhyBLT0PiDP0lyG1znv1NxSi5qjC/xYc/t6byrWP/8sbjmkgtdHoci4Nu0GSfUUU++BYbn9i87Vv1xtlFof2nkX3u5WrEBeYO+ZNDzS6HwHERFY9PKpnmzBp26CAHWKxmmnyFS+gPB7MqItADlRl9srSdaaHUMz0C1dQLIFXTJzJ7joVnKMaWRrZzkK0k23l5INdw8yYBKUK88TU0P8iGxApA0m9JXHtg7MQ+Djjel3rllLdwYlKk1APpp6DrdA/pGyILwo8FRuARD9oStmPpyXhXUn3nfrLdlfBdKsosc1Q5zDIerYU3RBtxY/UzH8yz6hl1Ybd9w4o7glCxBhaTmNehCqC5o1HZcaePlP0vapdrN2apdXlOLIEHt7BEMPeTaYaNcENYLwyXXrjz2sNpphwNeSu9kXU9/F98gJibFyQopdBWJIBK+LU6X5HwRbJhqL9fZj2nUIe4LqvrZoDVrb/Nz0zaZ1t+fyQc9viGcgNEGYbZcIChAKPqW8I5js/cggvApS9mDNl1oDuBvjFuvr9JG52JPRco2PO9Kf4aeHKX7JacZka0O3RzUINJXNVgkOaf+r45FLJg65heGA4/81mgeVSwOYMUKRaJ/ugfvGUd2LUXY6Awvsk9cjsqJxO1FNoxjJno3VS99M12P/9wm7NQW9uAaujQS5OKwt2DbFLJQ==
    plain-text-password-enabled: AgAisLo2ihFWNzdlCKUc9wFXbVHKDo7TzhBputggCe6JcHsngvXyvG2r/DMPJTsFd8EcCtSsdqhs5vo95DWdFM2HxBDoWDw4AOlmYqZULYXaIMUXRThFwetLEFlYK5oyn+5o5uKYusRWFu44ev8LcfPZNCZZTv2XFEwVJkK3elEv8euJlS+2OrppGBMKQsXhwXvfxPvzO7B6lXCEGKZzl+cfJHIAGKI2fcZajn2K8ejic+cBqfTE8iPsalBC0qYEnbZnTCnwgvw3CcmzVOF0mkC82zTMGn7auHyFxMnlwTZJ/Qa5b4/DWOIAwRzJ+Cr8WHl4RdoRS2aDZsXA0QkMlEwShh+eieyW171AAmAU8HLYs6wdOM1IYslo8IU2aE2AsHW909O36TGPmXhlYH5B2ioEcA483qyb7c9DDGuIGjpVqcxex9ho/doe9Zt2k2xH4dhw8VE6AMSVovW2LvWnrWyJM2lcFXsGA45yoBWSDrY8D4T71FVESWZsOYT3rmGMlA1a1tKEgcmP0gRbU3EKi7prsEYh7s5MJY/7CLDp/h1lbGuL0ex/lyaslt2HrRE+1dQMDBMOQr/lanqgNnqjBUIw8OwaZqffPxM5cxMfBRRGjLB0hA+SwBYiRR1XZONenSj0WnDF+ulWhl+9GfbT9vTiySYG+RI7NiB02Sgq5L4wijvyMfyQ0Wm2VRapj8I4tkUf6eZ3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quinoa-wind-turbine
        app.kubernetes.io/component: quinoa-wind-turbine
        app.kubernetes.io/instance: quinoa-wind-turbine
        app.kubernetes.io/name: quinoa-wind-turbine
        app.kubernetes.io/part-of: wind-turbine
        app.openshift.io/runtime: quarkus
      name: quinoa-wind-turbine
      namespace: gitops-demo-prod
    type: Opaque
{{- end }}