apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: wind-turbine-apps
  namespace: openshift-gitops 
spec:
  generators: 
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        namespace: gitops-demo-dev
        targetRevision: HEAD
        imageTag: "latest"
        followChangesForBranch: "main"
      - cluster: stage
        url: https://kubernetes.default.svc
        namespace: gitops-demo-stage
        targetRevision: HEAD
        imageTag: "Release-1.0.0"
        followChangesForBranch: "Release-"
      - cluster: prod
        url: https://kubernetes.default.svc
        namespace: gitops-demo-prod
        imageTag: "Release-1.0.0"
        targetRevision: HEAD
        followChangesForBranch: "" # -> empty means don't follow
  template:
    metadata:
      name: 'wind-turbine-{{cluster}}-app'
    spec:
      project: default 
      source:
        repoURL: "https://github.com/gmodzelewski/quinoa-wind-turbine-manifests"
        targetRevision: '{{targetRevision}}'
        path: helm
        helm:
          # valueFiles: 
          # - values.{{cluster}}.yaml
          parameters:
          - name: repoUrl
            value: 'https://github.com/gmodzelewski/quinoa-wind-turbine-manifests'
          - name: applicationGitUrl
            value: 'https://github.com/gmodzelewski/quinoa-wind-turbine.git'
          - name: image
            value: 'quay.io/modzelewski/quinoa-wind-turbine'
          - name: imageTag
            value: '{{imageTag}}'
          - name: followChangesForBranch
            value: '{{followChangesForBranch}}'
      destination:
        server: '{{url}}' 
        namespace: '{{namespace}}'
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: image.openshift.io
        kind: ImageStream
        jsonPointers:
        - /spec/tags
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
        - /spec/template/spec/containers/0/image