apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: wind-turbine-app
  namespace: openshift-gitops 
spec:
  project: default 
  source:
    repoURL: "<your-forked-manifests-repo>"
    path: helm
    helm:
      parameters:
      - name: repoUrl
        value: '<your-forked-manifests-repo>'
      - name: applicationGitUrl
        value: '<your-forked-app-repo>'
      - name: image
        value: '<your-mirrored-image>'
      - name: imageTag
        value: 'latest'
      - name: imageDigest
        value: '<the-image-digest>'
      - name: followChangesForBranch
        value: 'main'
      - name: disableSecretsDeployment
        value: 'true'
  destination:
    server: 'https://kubernetes.default.svc' 
    namespace: 'quinoa-wind-turbine'
  syncPolicy: 
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: image.openshift.io
    kind: ImageStream
    jsonPointers:
    - /spec/tags
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
