{{- if eq "gitops-demo-dev" .Release.Namespace }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quinoa-wind-turbine
  namespace: gitops-demo-dev
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    developer-user-password: AgBycERs0FumwiBZP8uonltA+f02X7WS1eCoRi5CmvLnOXndbMVBn/I/PmAKxUromUGSa9F6ARXQIpyoDQdTFOF5sQsOHmhr7UTschlYENCxvzaDk2tVBN+i5pPAoCbm6zgL/g6TkyvgMzH/DhbS0Wbl91bj4MGNPdPaMM/mxxr79ULdAYjpSexYsDpermRkp4kkcC7gEW1AUJDcfdt3/ZT38mq7y5opyHXHRy3TiUpuUIPLgYoAy922fkVwnDmI+KgCFZK9xpnPWZs7S86dvslCZ/kifWijGzTPslZ2hSR3r9ANxnuiiLY/3h6UKMNl6seepzFp1eE4NaHRUCU//G3D4U2/PKPTet2WBbFGak8E21TU7a554FElCp7BaXciC8quzYL29w67UW1taqVOaNL41qotp5PdAj7IWkYLSFVcHD80gmYIMh8HqUKpmIjsSHcP1cZKUiUyfc7v/vtuBOR2iQVNbWWuaFZZLw7aTIzGunE2vQTtYbQQXWkdrjwsKX8W+aozXL2qZzvvoGvnCcUtYrzhd+YEBnnXgrIWbEquckQ1PGvjiScFly8pRD+act3R5YPFd3FmfIfZPn5CpHwkuISk9LYO5h8qMlbSi4wStWzIQQ2iZqv70Jgd5fFTGfShZrjuGwLeQdY2V8Q41w3XSM9d0CZF5cCYMyLVpefvccxmVlGpRqpRYOJ140Z61J8ErGYfmloBig==
    plain-text-password-enabled: AgBVRQLjOQTUaph8Bhx1OaaA3j6T3RObzXB3V2Mz+xyYLTrJltLYAmQagxiayDcr8f6Iy9FU0TeRxG/95VrQTPiOThxblmw8UyTGJt+mf0BLRLUQdR2F5yKC6IJlj4vod3NR1/nOSkXTQ/ZDEvEtsWNn/1032sRBgX6WtMKLzPEBIQv7Vufo8Zg5uMHwMtFt7CXBKvBaVfJp+fU4ZWqyOs2vufqlKPMkWuqSo3k6sbPWh3ippRXa62nzOZ0wUJZjVVjtcpFydrCNHJzGoY46nybSrCRO2zJU4ALpVKSTflu6Kd3EEDltnhdvpEu3HugXAUndtsL+W8e1ZAT6j3btSov0FOeeIcqBJuSou63S8LVlq6dlfi7GfijfbixePHwYnFnr4j9iEySki6y+EMSKMeNP6QxA4+FYkdQDwcdBKTFpQFpKFjBCKpTGi0sRA316/HX9aCWf/Jehi707dbdOGPIHsQQkcHtNMGg6X9OQdvkVyXED7uLP13kLWjfqqcinOoLrNUIAYzVhXImomLUcYdJG661pnuotJX9rg9mhtvTMs8AcpvoD5qaicdq6xRNpFueDoEZUh7XXNaqKFc7h0+tv4JTeTSEaE3qAQKbpYTvewPN7r/KdYp6KfvRk4OiajjD/jb5IxPt2BaikANMyYFaddVy80OXlEIbtapXhL8s8vGC7GPNf/+XkpfK5SxOGeIQsiwSF
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quinoa-wind-turbine
        app.kubernetes.io/component: quinoa-wind-turbine
        app.kubernetes.io/instance: quinoa-wind-turbine
        app.kubernetes.io/name: quinoa-wind-turbine
        app.kubernetes.io/part-of: wind-turbine
        app.openshift.io/runtime: quarkus
      name: quinoa-wind-turbine
      namespace: gitops-demo-dev
    type: Opaque
{{- end }}
