apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-source
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi