apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-cache-pvc
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
