apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: wind-turbine
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: wind-turbine
    template:
      ref: wind-turbine
    interceptors:
    - cel:
        filter: >-
          (header.match('X-GitHub-Event', 'push') && body.ref.startsWith('refs/heads/{{ coalesce .Values.followChangesForBranch "main" }}'))