apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: wind-turbine
spec:
  params:
    - name: content-type
    - name: git-commit-message
    - name: git-repo-url
    - name: git-repo-name
    - name: git-revision
      description: The git revision. In trunkbased development, the release version.
      default: main
    - name: git-tag
    - name: pusher-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: wind-turbine-pipeline-
        labels:
          tekton.dev/pipeline: wind-turbine-pipeline
      spec:
        params:
          - name: IMAGE_TAG
            value: $(tt.params.git-tag)
          - name: GIT_REPO
            value: $(tt.params.git-repo-url)
          - name: GIT_BRANCH
            value: $(tt.params.git-revision)
        pipelineRef:
          name: wind-turbine-pipeline
        workspaces:
        - name: source
          persistentVolumeClaim:
            claimName: app-source
        - name: maven-settings
          persistentVolumeClaim:
            claimName: build-cache-pvc