apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wind-turbine
  namespace: openshift-gitops
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: {{ .Values.repoUrl | default "https://github.com/gmodzelewski/quinoa-wind-turbine-manifests" }} 
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true